Farigh/pokeclicker-automation

- src/lib/Menu.js
In some rare cases the button's state is changed while being disabled.
In such case, the button's class must not be updated, only its label.
Fixes #4
> Menu: Fixup disabled button not being greyed

- src/lib/Quest.js
Depending on the implementation, not having a strict ordering between
quest types would result in a non-deterministic output.
This would result, in some cases, to change the focused quest
at each loop cycle.
For some quests this would end into a dead-lock.
Fixes #1
> Quest: Fixup quest ordering algorithm

- src/lib/Utils.js
The player.town().region was used insteaded of the player.region
In some rare cases the town points to an old instance in another region
> Utils: Fixup the move to town method

- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Hatchery.js
- src/lib/Quest.js
- src/lib/Underground.js
- src/lib/Utils.js
Mutualize the Oak loadout management to Utils.OakItem
Mutualize route farming selection to the Utils.Route class
Improve the dungeon token and pokemon type farming route selection methods, by considering the pokemon attack in addition to the click attack (which is more relevant in end-game)
Add the module to the alert title, add the possibility to send warning alerts
> Utils: mutualize some code

- src/Automation.js
- src/ComponentLoader.js
- src/jsconfig.json
- src/lib/Click.js
- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Gym.js
- src/lib/Hatchery.js
- src/lib/Items.js
- src/lib/Menu.js
- src/lib/Quest.js
- src/lib/Underground.js
This feature replaces the 'Best route' one.
It is a button associated to a drop-down list of many possible focuses:
- Experience: Focus on earning experience to improve the player's pokemon
- Money: Focus on earning money fast (formerly the 'Best route' feature)
It now uses Gyms since they give way more money than routes
- Dungeon tokens: Focus on earning Dungeon tokens fast
- Achievements: Focus on completing achievements, the following achievement types are implemented:
- Route kill
- Gym clear
- Dungeon clear
- \<Type\> Gems: Focus on earning the selected \<Type\> of gems, fast
> Add the 'Focus on' feature

- src/lib/Quest.js
A player loading the mode for the first time might be pretty disturbed
otherwise, as most menu would be greyed, the player would be moved 
to places....
This is not a suitable default setting, so it's now turned off by default
> Quest: Disable 'AutoQuests' mode by default

- src/lib/Dungeon.js
- src/lib/Menu.js
The pokeball image in now clickable to switch from pokemon to shiny.
A glow was added to notice the user that the image can be clicked.
Fixes #11
> Dungeon: Add the possibility to stop on shiny completion

- src/lib/Underground.js
If the player buy the 'Larger underground' upgrade, the underground layout gains a row.
This is not reflected on the static property (which reflects the default row number).
The algorithm would be stuck in such case since it would never consider the last row.
The getSizeY method, which gives the number of rows based on the unlocked upgrades is now used.
> Mine: Fix the algorithm for larger underground

- src/lib/Dungeon.js
If the player is catching the boss, a user action was wrongfully
detected, even though all tiles were visible.
Any action is now disabled while in catching state.
> Dungeon: Fixup user action detection false positive

- src/lib/Underground.js
The size of the underground only increases on the next mine layout refresh.
The size of the current mine layout is now used instead of the underground attribut that define the size unlocked by the player.
> Mine: Fixup crash when the the Larger Underground is unlocked

- src/lib/Dungeon.js
If the player has the flashlight (after defeating the dungeon more than 200 times), the tiles nearby the player are visible.
When entering a dungeon, if the boss is on a tile directly adjacent to the entrance, the script would rush for it immediately, since it's visible.
In case the player never moved, it's not the intended behavior.
The dungeon is now only tagged as completed if either:
- It's not the first moved
- Or:
- The boss tile is visible or visited
- The player visited at least a tile (apart from the entrance)
Fixes #31
> Dungeon: Fixup player rushing to boss in some rare cases

- src/lib/Focus/Quests.js
The list was compared to 1 instead of the length of the list
Fixup #33
> Focus.Quests: Fixup oak item not being selected

- src/lib/Dungeon.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
If the player enabled the 'stop on pokedex' option and a quest or an achievement needed to complete a dungeon in which all pokemon were caught, the button wass disabled and the dungeon would never start.
The automation can now request to bypass the user settings for dungeon
Fixes #30
> Focus.Achievements: Bypass the player's stop on pokedex option

- src/ComponentLoader.js
- src/lib/Focus.js
- src/lib/Focus/Quests.js
- src/lib/Utils.js
- src/lib/Utils/Gym.js
Gyms give way more gems per kill.
If no gym is available for a given gem type, the route will be considered as before.
Fixes #22
> Focus.Gems: Use gyms in priority to farm gems

- src/lib/Dungeon.js
If the player is still in the dungeon, he won't be able to turn the feature off if needed.
The button is now disabled only if the player is not within a dungeon instance
Fixes #41
> Dungeon: Don't disable the button if the player is still in the dungeon

- src/lib/Menu.js
The toggle buttons could not be disabled, and using the regular
disable function was setting an incorrect theme to it.
The toggle buttons now have their own disable theme and function.
The module still uses the same method but it will dispatch to the
correct one depending on the button class.
> Menu: Add disable support for toggle buttons

- src/lib/Focus/Achievements.js
The gym can be listed because the town was unlocked, but still be locked.
The gym unlocked state is now checked in the achievements filter.
---
On Chrome, the initial order was not preserved after the reorder call.
This was due to not handling equals elements properly, which is the only way to preserve the order.
Fixes #56
> Focus.Achievements: Fixup the achievements filtering method

- src/lib/Focus/Achievements.js
In case the gym is a league, multiple gyms are tied to the same town.
In such case the gym name must be used to gate the gym info, not the town name.
This regression was introduced by #59
> Gym: Fixup league gym achievements

- src/ComponentLoader.js
Running the game on a low-end environment (a raspberry pi for instance) can take a significant amount of time before it's up and running.
This could cause the menu to request game components that are not yet existing or instantiated.
The loader now makes sure the game is properly loaded before loading the automation.
> Loader: Don't load and run before the game is fully instantiated

- src/lib/Farm.js
While the `Focus on quest` feature is enabled, the script will switch to Cheri berries to avoid occupying the farm with long riping ones.
It also asks the Farming automation to harvest berries as fast as possible.
However, this parameter was not considered by the harvest method.
It's now properly done.
> Farm: Fix the harvesting method while doing quests

- src/lib/Dungeon.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Utils/Route.js
If the player was already in the right town, he would be moved anyway.
This broke gym automation if the player could not kill all pokemon fast enough, since moving in such case would reset the gym.
The player is not moved anymore if already in the right town.
Fixes #67
> Utils.Route: Don't move the player not necessary

- src/Automation.js
- src/ComponentLoader.js
- src/lib/Click.js
- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Gym.js
- src/lib/Hatchery.js
- src/lib/Items.js
- src/lib/Menu.js
- src/lib/Shop.js
- src/lib/Underground.js
- src/lib/Utils.js
The shop settings are available in its advance settings panel:
The green checkmark is displayed to notice the user that the changes have been saved for the current setting row.
It will be done after 3s without any changes in said row.
If a value under the minimum possible base price is entered, the value will turn red and be reset to the minium value after 1s without further modification :
The shop automation will run every 10 seconds and buy according to the user settings.
If anything was bought, a notification is sent with the amount spent:
closes #52 
fixes #45
> Shop: Add a new Shop auto buy feature

- src/lib/Focus.js
- src/lib/Focus/Quests.js
- src/lib/Utils/Gym.js
- src/lib/Utils/Route.js
In some cases, farming routes can be more efficient than farming gyms.
Both rates are now computed and the best one is chosen.
---
The player can't get any gems until the Gem_case key item was unlocked.
The focus topic is now hidden until the in-game functionality has been unlocked.
Fixes #47
> Focus.Gems: Consider both gym and route

- Readme.md
- src/lib/Dungeon.js
`DungeonRunner.map.hasAccesToTile` was renamed `DungeonRunner.map.hasAccessToTile`
Fixes #75
> Update code to support v0.9.8 changes

- src/lib/Trivia.js
The roamers can now be different depending on the player subregion.
This will be used in the upcoming Galar region.
The methods were changed accordingly in v0.9.8.
This commit uses the new methods to get the roaming pokemon info
Fixes #77
> Trivia: Fixup roaming pokemon info

- src/lib/Dungeon.js
If the player started a dungeon with the button disabled, it would never be enabled again, keeping the player from turning the feature on or off.
This could happen if the player entered the dungeon manually while a stop option had its requirements met.
> Dungeon: Fix button never re-enabling while in dungeon

- Readme.md
- src/lib/Hatchery.js
- src/lib/Utils/LocalStorage.js
This option will add contagious Pokémon if none are present in the hatchery.
It will then add Pokérus-free ones matching the contagious pokémon type to spread the pokerus to them.
Once every pokemon have been infected, it will fallback to the default strategy.
This option is togglable in the advanced settings and is on by default.
Since the Pokérus is an end-game unlock, the option is disabled until the player reached this point.
Fixes #63
> Hatchery: Add Pokérus speading strategy

- src/ComponentLoader.js
- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Focus/Quests.js
- src/lib/Gym.js
- src/lib/Hatchery.js
- src/lib/Items.js
- src/lib/Menu.js
- src/lib/Shop.js
- src/lib/Trivia.js
- src/lib/Underground.js
- src/lib/Utils/Gym.js
- src/lib/Utils/OakItem.js
- src/lib/Utils/Route.js
For-of loops are way more readable and don't have tricky edge cases.
As for regular loops break and continue keyword works.
Some hacky use of every() were replaced with for-of loops.
---
A performance issue of the `moveToHighestDungeonTokenIncomeRoute` was addressed as well.
This method generated huge spikes in the profiler:
The callgraph shows that most of the time was spent accros 2 methods:
The `calcBonus` method is a pokeclicker method. The call always returns the same value.
To avoid performing such computation each time, the data is computed for all routes at the start of the automation and stored in a map.
This reduced the spike considerably:
The `calcBonus` is not involved anymore:
The `getPlayerWorstPokemonAttack` might be worth optimizing though.
The responsible call is …
> Coding style: Replace foreach usages

- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Utils/Route.js
The new option is available through both Farm and Focus advanced settings.
The associated option only toggles the oak item management for the set feature.
Indeed, some player might want to keep one or the other feature's auto-equip.
Fixes #91 
---
Farm: Fixup oak item loadout being messed-up
The loadout was always reset because the item id was compared to the item object, which was obviously always different.
The custom loadout was a mix of items and item id.
Thus, only the needed item was equipped back because the `activate()` method takes the item's id as param, not the item object.
Only the last item of the current loadout is removed now, only if there is no room for the needed item.
> Farm/Focus: Allow player to disable oak item loadout modification

- src/lib/Underground.js
The current Hammeruse Logic leads to inefficiencies. This PR intends to increase the mining efficiency by comparing the hammer use benefit to just chiseling out the tiles. 
The main difference here is that the hammer breaks 1 layer of each tile while the chisel breaks 2. So under ideal circumstances the hammer would need to hit 6 tiles each time to make up for 3 chisel uses. However if the hammer hits a tile with an uneven amount of layers on it it is effectively equivalent to a chisel hit there.
This commit adds the amount of layers on each item tile to the logic, and checks in the considerHammerUse how efficient each Hammer hit is compared to just using Chisel
> Mine: Improve most efficient tool selection

- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Shop.js
- src/lib/Trivia.js
Add an option to define the ball to use to catch pokémons
The Ultraball was used by default, which might be a bit too expensive
early game.
An advanced option is now available to now choose which ball to use.
This will only affect selection when no particular ball is needed.
Fixes #93
---
Add an option to define the ball when no catching is needed
No ball was used by default, which might be ineffective when trying to
grind EVs while focusing on some topic.
An advanced option is now available to now choose which ball to use.
This will not affect the default value when focusing on quests.
Fixes #93 
---
Shop: Fixup feature being unlocked too early
The unlock condition was on "Cinnabar Island" city unlock.
However, the Poké Mart shortcut is only available upon beating
the league "Champion …
> Focus: Add pokeball advanced settings

- src/.vscode/settings.json
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Shop.js
The shop feature should only be visible once the Poké Mart has been unlocked.
The status checked is an observable, it needs to be called to
be accessed. This is now done properly.
This is a regression from #96
---
Fixup a case were the player would have the dungeon button disabled 
right away, and have to click it again to effectively enable the feature.
> Shop: Fixup shop always being visible

- src/lib/Farm.js
Mutations requires the berries involved to be ripe to occur.
However, the target berry should be harvested as soon as it ripes, to avoid any possible unwanted mutation.
Fixes #99
> Farm: Harvest target berry as soon as it ripes

- src/lib/Farm.js
- tst/stubs/Farming/FarmController.pokeclicker.stub.js
The plotClick function now takes a MouseEvent additional parameter.
This was added by pokeclicker [plot locking feature implementation](https://github.com/pokeclicker/pokeclicker/commit/7a2f9043a52854a3e11abc078dec77f11e332338#diff-da5cb4cb6f02bf9239bf779ec92a8b1a9878946a5c25b91fed13bcfbefb29a2dR87-R95).
> Farm: Fixup v0.9.11 regression

- src/lib/Dungeon.js
- src/lib/Hatchery.js
- src/lib/Menu.js
- src/lib/Trivia.js
- tst/Hachery/AutoHatchery.test.in.js
- tst/stubs/GameConstants.pokeclicker.stub.js
- tst/stubs/Hatchery/Breeding.pokeclicker.stub.js
- tst/stubs/Pokemon/Party.pokeclicker.stub.js
- tst/stubs/Pokemon/PartyController.pokeclicker.stub.js
- tst/utils/PokemonLoader.utils.js
Until now, only the Pokerus and shiny toggles allowed players to tune the hatchery algorithm.
This PR adds the following additional settings:
- Prioritizing pokémons from a specific region
- Considering regional attack debuff
Partially addresses #48
> Hatchery: Allow the user to set region-related filters

- Readme.md
- src/lib/Utils/Route.js
- tst/stubs/Pokemon/DataPokemon.pokeclicker.stub.js
- tst/stubs/Pokemon/PokemonHelper.pokeclicker.stub.js
- tst/stubs/Pokemon/TmpPokemonListData.pokeclicker.stub.js
- tst/stubs/Route/Routes.pokeclicker.stub.js
- tst/tests/Utils/Route.test.in.js
- tst/utils/PokemonLoader.utils.js
The Sevii Island 456 has a max health of an Hoenn-level route.
The previous implementation relied on the game's `regionRoute` list being ordered by max health. This is not possible anymore.
The internal data was changed to a list, ordered by max health to fix the problem.
Fixes #126 
---
Added some tests to the `moveToBestRouteForExp` method
> Utils.Route: Fixup v0.9.14 regression

- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Shop.js
- src/lib/Underground.js
- tst/imports/Pokeclicker.import.js
- tst/stubs/GameConstants.pokeclicker.stub.js
- tst/stubs/Items/BattleItem.pokeclicker.stub.js
- tst/stubs/Items/EnergyRestore.pokeclicker.stub.js
- tst/stubs/Items/PokeballItem.pokeclicker.stub.js
- tst/stubs/Statistics.pokeclicker.stub.js
- tst/stubs/Town/PokeMartShop.pokeclicker.stub.js
- tst/stubs/Town/Shop.pokeclicker.stub.js
- tst/tests/Shop/AutoShop.test.in.js
A new advanced setting panel was added to the Mining feature.
This panel contains two toggles:
- Automatically use restore items
- Only use restore items when a mining quest is active
Both are enabled by default.
The Focus "Automatically buy and use small restores" advanced setting was removed.
Note: The restore items can automatically be bought using the "Auto shop" feature.
Fixes #109
---
The auto shop feature was adapted to allow the player to by items right after they've been unlocked instead of having the wait for the Poké Mark in-game shop to be unlocked
> Mine: Add a "Use restore items" advanced setting

- src/lib/Hatchery.js
- src/lib/Underground.js
- tst/tests/Hachery/AutoHatchery.test.in.js
The player can now choose to breed pokémons from a specific type in priority.
If a region priority is set as well, and no pokémon of the selected region and type can be hatched, the algorithm will select pokémons from the such region before ones matching the type.
Partially addresses #48
> Hatchery: Add a type priority setting

- src/lib/Farm.js
- tst/tests/Farm/UnlockStrategies.test.in.js
The more berries involved, the harder it becomes to trigger a mutation without synchronizing the berries timing.
This PR implements the ripe time synchronizing.
Main part of #88
> Farm: Synchronize berries riping time

- src/Automation.js
- src/lib/Farm.js
- tst/tests/Farm/UnlockStrategies.test.in.js
- tst/tests/Hachery/AutoHatchery.test.in.js
If a berry is on a plot involved in the strategy, or if a berry is in another plot but will rip after the strategy ones, the strategy will not start planting anymore.
Partially implements #88
> Farm: Don't perform mutation strategy if an unneeded berry is present

- Readme.md
- src/lib/Dungeon.js
- src/lib/Farm.js
Galar dungeon can have multiple floors.
This commit fixes the behaviour for the current state of the game. 
However multiple floors needs to be handled to prevent any additional regression once Galar (and dungeon over 9 tiles wide) are available.
Fixes #140
> Dungeon: fixup v0.9.18 regression

- src/lib/Focus.js
- src/lib/Focus/Quests.js
- src/lib/Menu.js
The Focus advanced settings now have a Quests tab.
The list of every possible quest types are listed there, and the user can choose which one to enable and which one to skip.
By default, every quests are enabled.
If the user disabled a quest, it will not be automated, even if it's already in the active list.
If every enabled quests are completed, the list will automatically be refreshed.
Fixes #20
> Focus.Quests: Allow the user to disable quests

- Readme.md
- src/lib/Hatchery.js
The partyPokemon member access was changed to a KnockoutObservable by pokeclicker/pokeclicker@ad2555ee764c3ec4c8376c7a00adef8fa60c0cec
This resulted in not detecting currently breeding infected pokemons, which prevented corresponding pokemons to be added.
For some reason this was not caught by the tests, the behavior might be browser-dependent.
The member is now accessed properly
Fixes #153
> Hatchery: Fixup pokerus spreading feature

- src/lib/Focus/Quests.js
The pokéball default value from general settings was not used for quest that did not require catching pokémons.
Catching was disabled in sure case.
The set value is now used in those cases as well.
Fixes #156
> Focus.Quest: Use the pokéball default value from general settings

- Automation-UserScript.js
- src/Automation.js
- src/ComponentLoader.js
- src/lib/Focus/Quests.js
- src/lib/Menu.js
The Loader now exposes a new variable allowing the user to disable every features by default.
If not set the value will be considered to be false (for backward compatibility purpose)
This variable is set to false by default
Fixes #152
> Loader: Allow the user to choose to disable feature by default

- src/lib/Click.js
The Click automation now clicks while in a temporary battle.
> Click: Autoclick in temporary battles

- src/lib/Farm.js
Bug introduced in c43c7e29a785e19b11065d5700884447d7dc4539
Currently, when farming is set to no strategy, the script fails when checking if it should harvest the berries or not, and farming no longer works at all
Feel free to reorder the conditionals in any other way, they are hard to understaund
> Farm: Fix harvesting error when no-strategy is set

- src/Automation.js
- src/ComponentLoader.js
- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Hatchery.js
- src/lib/Notifications.js
- src/lib/Shop.js
- src/lib/Underground.js
- src/lib/Utils.js
- tst/tests/Farm/UnlockStrategies.test.in.js
- tst/tests/Hachery/AutoHatchery.test.in.js
Allows having the notifications enabled but only for some modules.
By default, any notification whose module is not recognized will be shown.
> Notifications: Split Notifications settings and add advanced options

- src/lib/Focus/Quests.js
If Quest focus gains a quest targeting a later elite 4 member (or champion) it would move the player to the league and activate auto fight before selecting the correct member. This would result in these quests always doing a run through the first elite 4 member before switching to the correct member. Fixed by first selecting the right member before activating the autogym battle setting.
> Fix for Elite4 Quests starting on wrong member

- src/lib/Underground.js
As the timer is for 5 minutes, it may look to the users that the auto-trade option is not working.
Manually triggering it when the options are changed is an easy way to fix this usability problem
> Mine: Automatically trigger the trade when changing options

- src/lib/Underground.js
To improve general mining efficiency hammer logic should be allowed to hit already completely revealed tiles. An easy example, following tile setup:
111
101
111
With the current logic this would use the the equivalent of 2 hammer actions worth of energy, since currently the hammer cannot hit the already revealed central tile. With this change that tile would also be considered and only 1 hammer action would be necessary to completely reveal all tiles.
> Improve Mining efficiency: Let Hammer consider revealed tiles

- .github/workflows/tests.yml
- src/lib/Farm.js
- src/lib/Menu.js
- tst/tests/Farm/UnlockStrategies.test.in.js
- tst/utils/farming.utils.js
Some berries cannot be farmed by planting them, as they will only grant 1 berry that way.
New strategy steps were added for those. It will plant the berry if none are present and will surround them with Passho berries to increase their harvest rate.
> Farm: use Passho strategy to farm low rate berries

- Readme.md
- src/lib/Dungeon.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
A image is worth a thousand words, and a video is worth a thousand images, so... one million words?
(Any small pause in the exploration is a fight)
Fixes #124 as per the last sugestion:
* Visit the non-enemy tile that will reveal the most amount of tiles (min 1)
* Visit any enemy tile that will reveal the most amount of tiles (min 1)
Still have to polish how the switches interact with the exploration. Probably we will need a third switch to toggle whether to kill all non-bosses (or reword the switches?).
It does nothing if flash is not unlocked for the dungeon.
> Dungeon: Improve dungeon speed with flash

- src/lib/Trivia.js
The bulletin board was never hidden if no bulletin board quests were available on startup.
This was caused by using the same value as the default one to discriminate whether the div should be hidden or not.
The div is now hidden by default.
> Trivia: Fixup bulletin board not being properly hidden

- src/Automation.js
- src/ComponentLoader.js
- src/lib/BattleCafe.js
- src/lib/Menu.js
- src/lib/Trivia.js
- src/lib/Utils.js
This new panel will be displayed before the main menu. It will only be shown while the battle café modal is visible.
It will display the available unlocks of the currently selected sweet and their caught status.
Hovering the text will give more details: 
Fixes #181
> BattleCafe: Add battle café panel

- src/lib/Shop.js
The value was not renamed properly, resulting in a crash:
`Uncaught ReferenceError: itemName is not defined`
The right name is now used
> Shop: Fixup item name

- src/lib/Shop.js
The following error was issued while having pokémart items enabled:
Uncaught TypeError: this.__internal__isPokeMarkUnlocked is not a function
The class is now bound properly
Fixes  #184
> Shop: Fixup regression

- src/lib/Focus/Achievements.js
- src/lib/Menu.js
- src/lib/Shop.js
- src/lib/Utils/Route.js
Shop: Hide tabs with no items
Items are not displayed until they can actually be purchased.
Some tabs can have no items early game.
Tabs with no items are now disabled.
---
Focus.Achievements: Always display this feature
Achievements can be unlocked right away,
only the tracker needs to be unlocked.
The feature is now always available.
Only the tacker assignment is now conditioned.
---
Focus.Achievements: Fixup achievement never being selected
The achievement region was not retrieved using the right path.
The value would then be undefined.
If the given region was undefined, the canMoveToRegion would return
true on some browser.
The canMoveToRegion function now make sure the given region is a number
to ensure a consistent behaviour between browsers.
The region property is now accessed …
> Some improvements and bug fix

- src/lib/Focus/Achievements.js
As for the route achievements the region was not accessed properly. The region in now retrieved from the corresponding town.
Fixes #191
> Focus.Achievements: Fixup gym and dungeon quests not being selected

- src/lib/Menu.js
The color inversion is here to fit the dark theme, it's only relevant for the uncaught status image
The image was displayed this way : 
It's now only inverted for the uncaught status :
> Menu: Only inverte colors for uncaught status image

- Readme.md
- src/lib/Farm.js
- tst/stubs/Farming/Farming.pokeclicker.stub.js
- tst/stubs/Farming/Plot.pokeclicker.stub.js
Also restructured condition on when to harvest berries. The new version should be much easier to follow.
The new condition should still work the same, but I have not run the tests because they are not setup to be easy to run from outside the github workflow. I might take a stab on making the tests a one-comand to run later.
> Farm: add option to harvest late when not unlocking

- src/lib/Hatchery.js
While this removes using the megaStone to check for completion, it is necessary to actually perform the check
The issue that was (is) happening, is that when checking for a pokemon whose megaStone we do not have yet, calling `requirement.isCompleted()` will call `getProgress()`, which will return `App.game.party.getPokemonByName(this.name)?.megaStone?.canEvolve() ? 1 : 0;`. However, as the pokemon does not have the megaStone yet, the `canEvolve()` is never even called, and it always returns 0, never bothering to check.
Instead of checking for the hardcoded 100, we could create a new MegaStone object (without assigning it to the pokemon) and call the `canEvolve()` there, but that could make the scripts crash if the constructor is ever changed.
So we have two options to respond if this code …
> Hatchery: Fix mega evolution requirement check

- Readme.md
- src/lib/Focus/Quests.js
- src/lib/Hatchery.js
- src/lib/Utils/Battle.js
- src/lib/Utils/Gym.js
- src/lib/Utils/Route.js
- tst/imports/Pokeclicker.import.js
- tst/stubs/AchievementHandler.pokeclicker.stub.js
- tst/stubs/Pokemon/Multiplier.pokeclicker.stub.js
- tst/tests/Utils/Battle.test.in.js
- tst/tests/Utils/Gym.test.in.js
- tst/tests/Utils/Route.test.in.js
When the player does not have balls anymore and needs to buy some
but does not have enough money to do so, it was still moved to the
pokemon catching place, with the corresponding loadout.
It will now move to the money farming place and equip the money
farming loadout.
---
Battle: Fixup clickattack computation
The click attack value is now different in one sub-region.
This would result in the game moving back and forth from one route/gym to another if the region switched to the Magikarp jump one in the process.
This new setting is now used properly.
---
Fixes #207
> Focus.Quests: Move to the appropriate place to farm money 

- src/lib/Click.js
The player.starter member got replaced by regionStarters in v1.10.4.
One occurrence was missed when migrating to the scripts to the new member.
> Menu: Fixup 'player.starter is not a function' error

- src/lib/Click.js
- src/lib/Menu.js
- src/lib/Shop.js
When the player switches region, the previous regions shop are not available until the docks of the new region are unlocked.
A visual indicator is now displayed in front of each impacted items to inform the user.
> Shop: indicate when an item can't be bought

- src/lib/Shop.js
The update function was not updated once other currencies where added, thus the value was never updated.
The value is now updated according to the associated currency.
---
References to the old value from before the update were removed.
Fixes #213
> Shop: Fixup min player currency value not being saved

- src/lib/Utils/Gym.js
Trials are temporary gym fights that will only be available once.
They were correctly filtered in the findBestGymForMoney method
but not in the findBestGymForFarmingType one.
It's now filtered in both cases.
Fixes #211
> Utils.Gym: Do not consider trials as valid gyms

- Readme.md
- src/lib/BattleCafe.js
The battle café days used to be from 5h to 19h.
Since v0.10.7 they were normalized to be consistent with the rest of the game.
They are now from 6h to 18h.
Additionally, the Dusk time is now at 17h (19h before)
Fixup #216
> BattleCafé: Fixup regression from v0.10.7

- src/lib/Trivia.js
pokeclicker continues it's conversion to modules.
The getPokemonsWithEvolution method was moved to the PartyController.
Fixes #227
> Fixup v0.10.9 regressions

- Readme.md
- src/ComponentLoader.js
- src/lib/Dungeon.js
- src/lib/Farm.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Hatchery.js
- src/lib/Items.js
- src/lib/Shop.js
- src/lib/Underground.js
This feature will automatically move to routes were there is at least
one infected pokémon that is not resistant to the pokérus.
It will equip the set pokémon catching pokéball and catch every
pokémon on that route until the full route is resistant.
It will then move to the next route.
---
Misc: improve interval delay
Always call the method once for long delay to avoid the
feature lag impression.
Always call the method AFTER the interval setting to avoid
side effects.
---
Focus: Fixup some element naming to match accessibility
Some internal data/function were accessed by other focus sub-classes.
The __internal part of those element was removed
Partially adresses #122
> Focus: Add the Focus on Pokérus cure feature

- src/lib/Dungeon.js
The v0.10.9 introduced a new flash tier mechanics that broke the script. 
The flash strategy is disabled for now, it will be fixed in a later commit.
Fixes #231
> Dungeon: Disable the flash strategy

- src/lib/Dungeon.js
To avoid breaking the regular dungeon strategy, user action had to be detected to ensure proper dungeon completion.
In case the user has the flash-light with at least the second update (introduced in v0.10.9), the user action detection can be triggered when the player did not do anything.
This check is not relevant and have been removed in such case.
Fixes #235
> Dungeon: Don't stop anymore on user action when having the flash light

- src/lib/Trivia.js
The v0.10.9 started listing the stone evolution that have unmet requirements.
To avoid bothering the player with such info, the mega-evolution ones are now filtered.
Fixes #229
> Trivia: Filter locked mega-evolution listing

- src/lib/Focus/PokerusCure.js
The parameter to only consider contagious pokémons was missing when selecting the next route.
The filter was applied on Infected pokémons instead of Contagious ones. 
Only contagious pokémons can gain EVs.
Fixes #239
> Focus.PokérusCure: Fixup unavailable pokémon not being filtered

- src/lib/Focus.js
- src/lib/Focus/Achievements.js
The user can now choose to complete the Magikarp Jump sub-region requirements last.
Additionally, forces the magikarp content to be performed at the same time as the Galar content by default.
Any unhandled sub-region will now always be considered last.
Fixes #240
> Focus.Achievements: Add a setting to do Magikarp Jump content last

- src/lib/Farm.js
- src/lib/Notifications.js
- tst/imports/Pokeclicker.import.js
- tst/stubs/Automation/Menu.stub.js
- tst/stubs/Farming/EnigmaMutation.pokeclicker.stub.js
- tst/stubs/Farming/Farming.pokeclicker.stub.js
- tst/stubs/Farming/Mutation.pokeclicker.stub.js
- tst/tests/Farm/UnlockStrategies.test.in.js
In some cases the berry needs certain conditions to be met before being able to unload it.
The script will now disable itself when such case is not handled properly.
---
The pinkan berry requires a certain quest to be completed before it can be unlocked.
Since this berry is not needed by any other unlocks, it's been made optional and the next strategy will be picked if this berry is not yet unlocked.
> Farm: Disable the unlock automation when the berry can't be mutated

- src/lib/Hatchery.js
In real evolution challenge, the base pokémon stats gets transferred
to the evolution. The base attack of the base pokémon gets reset.
The hatchery will no longer consider those pokémons if the challenge is enabled.
In the standard mode, the already unlocked evolutions will still be selected. This is done because the game might change the requirements and this would keep players from being able to farm the shiny form this way.
---
Rework hatchery sorting implementation
A list of sorting function is now created and iterated through. This will allow reordering filters in the future.
Partially addresses #238
> Hatchery: Don't farm unlocked mega-evolution in real evol challenge

- src/Automation.js
- src/lib/BattleCafe.js
- src/lib/Menu.js
The panel is now displayed on the left side of the modal. It will always be vertically centered so the panel is always visible.
> BattleCafe: Display the panel next to the in-game modal

- src/lib/Focus/Achievements.js
- src/lib/Utils/Route.js
In one case the `isUnlocked()` check was forgotten. 
To avoid this mistake again, a new method `canMoveToRoute()` was added
Fixes #249
> Utils.Route: Fixup unaccessible route detection

- src/lib/Dungeon.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Utils/Battle.js
The contagious pokémon ball needs to be set as well as the already
caught pokémon one.
It's now the case.
---
Add a setting for already caught contagious ball to use
Since the introduction, in-game, of the already caught contagious
pokémon pokéball selection, the user could want to restore different
ball for each cases.
Fixes #255
> Dungeon/Focus: Equip ball for contagious pokémon as well

- src/lib/BattleCafe.js
- src/lib/Farm.js
- src/lib/Menu.js
- src/lib/Underground.js
- src/lib/Utils/Gym.js
- tst/stubs/document.browser.stub.js
- tst/tests/Farm/UnlockStrategies.test.in.js
This new floating panel will give the user more information about
the current automation state
This panel will only be visible when:
- The farm in-game modal is visible
- The farming automation is enabled
---
Menu: Improve floating panel position
The floating panels can now no longer go past 200px from the top
to avoid weird positioning on high-res screens.
The panels will now be moved on screen resize with a 30px margin
from the bottom, to match the in-game modal.
> Farm: Add floating panel to the in-game modal

- src/lib/Farm.js
- tst/tests/Farm/UnlockStrategies.test.in.js
The Lum berry is really inefficient to farm using it's mutation strategy. 
The automation now uses the Passho one, once the player gets at least 1 Lum.
> Farm: Farm lum berries using the Passho strat

- src/lib/Utils/Battle.js
- src/lib/Utils/Gym.js
- src/lib/Utils/Route.js
- tst/tests/Utils/Battle.test.in.js
- tst/utils/jest.extensions.utils.js
The magikarp jump region could be selected to farm gems in case were it's not relevant.
This commit introduces the MagikarpJump special region to the `getPlayerWorstAttackPerSecondForAllRegions` method results.
Fixes #260
Part of #209
> Focus: Handle magikarp jump region for gym gem farming

- src/lib/Focus.js
- src/lib/Focus/PokerusCure.js
Such pokémons can only be caught using a Beastball. Those can only be bought using quest points.
An advanced setting was added to allow capturing UltraBeasts.
If the player did not enable this new setting or has no Beastball left, UltraBeast pokémons will be ignored.
Part of #122
> Focus.PokerusCure: Add support for UltraBeast pokémons

- src/lib/Farm.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Menu.js
- tst/stubs/Farming/FarmController.pokeclicker.stub.js
- tst/tests/Farm/UnlockStrategies.test.in.js
The in-game selected berry should not be used for the automation.
This value can be tempered with easily, by simply navigating between
pages for example.
Moreover, this data is reset each time the app is closed,
it's not persisted.
An advanced setting is now used for that purpose.
---
Farm: Don't use the selectedBerry to force berry planting
Forcing a berry planting would override the in-game user-selected
berry.
The ForcePlantBerriesAsked now contains the berry type directly,
this value is then used to plant berries insteadn of using
`FarmController.selectedBerry()`.
---
Menu: Add custom dropdown list creation method
Regular HTML select element can only contain options with text content
The `createDropdownListWithHtmlOptions` method can be used to create
dropdown lists containing …
> Farm: Don't use the in-game selected berry anymore

- src/lib/Farm.js
- src/lib/Focus/PokerusCure.js
The Magikarp Jump can bit a bit tedious to farm, it's now considered last.
> Focus.PokerusCure: Perform Magikarp Jump routes last

- src/lib/Focus/PokerusCure.js
- tst/utils/PokemonLoader.utils.js
Pokémon alternate forms can now be skipped entirely thanks to this now advanced setting toggle.
Part of #122
> Focus.PokerusCure: Add an advanced setting to skip alternate forms

- src/lib/BattleCafe.js
It was displaying '1-4 counter-clockwise' were it's actually '11+ counter-clockwise'.
Fixes #271
> BattleCafe: Fixup Dusk spin description

- src/lib/Farm.js
The in-game `App.game.farming.unlockedBerries` function can return `undefined` when the berry has not been unlocked yet.
This would collide with the default value,
resulting in the panel not being updated.
The value is now converted to a boolean to avoid such case.
> Farm: Fixup the floating panel not refreshing in some cases

- src/lib/Farm.js
- src/lib/Menu.js
- tst/stubs/GameConstants.pokeclicker.stub.js
- tst/stubs/document.browser.stub.js
The user might wander what strategy is currently used by the automation to unlock the currently selected berry.
This information is now displayed under the current berry name in the floating panel, for the mutation strategies.
Hovering a berry will display a tooltip with its name and the delay before planting it compared to the first planted berry (if applicable)
Fixes #274
> Farm: Display the plantation strategy in the floating panel

- src/lib/BattleCafe.js
The floating panel displayed it as a random unlock where it's actually a predefined spin count requirement.
> BattleCafe: Fixup Milcery (Cheesy) requirements

- src/lib/BattleCafe.js
- src/lib/Menu.js
- src/lib/Utils.js
The panel now shows the pokérus status when available : 
Fixes #279
> BattleCafe: Add pokérus status to the floating panel

- src/lib/Focus/Quests.js
- src/lib/Hatchery.js
- src/lib/Trivia.js
- src/lib/Utils.js
The mega-evolution requirements need to be reached twice:
- The 1st time to mega-evol the pokémon (resulting in loosing the required stat on the base pokémon)
- A 2nd time to allow EV farming
An advanced setting is now available to set the wanted behaviour. 
Since this behaviour is only relevant in real evolution challenge, the setting will only be shown in this case.
Fixes #283
> Hatchery: Add an option to keep farming for mega requirement

- src/lib/Shop.js
The refactoring performed when adding new currency support (commit 28f6928a3e941248fc4849c7d7e5997a0d1cb254) broke the feature.
Some variables were not considered and were unreachable.
The html elements were regrouped in a new `itemData.htmlElems` sub-member of the `itemData`.
Those variable are now part of `itemData.htmlElems`:
- `checkmark`
- `buyCount`
- `untilCount`
> Shop: Fixup input not updating values

- Readme.md
- src/ComponentLoader.js
- src/lib/Dungeon.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Utils.js
- src/lib/Utils/Battle.js
- src/lib/Utils/Pokeball.js
- tst/imports/AutomationUtils.import.js
The v0.10.11 reworked pokéball selection filter to allow custom filters 
This broke the automation ball selection mechanism.
This commit adds an automation filter, that will be disabled by default 
The automation will now configure the filter proper and enable it when it's needed.
Default pokéball value settings are not relevant anymore, they've been removed.
---
The Focus.Quests now restrict the filter pokémon type when focusing on a `CapturePokemonTypesQuest`.
Fixes #293
> Utils: Implement automation pokeball filter

- src/lib/Focus/PokerusCure.js
- src/lib/Utils/Route.js
Some locations might not be accessible yet,
either because they are locked, or the region is not accessible.
The automation will not consider such candidates anymore.
Fixes #298
> Focus.PokerusCure: Don't try to move to inaccessible locations

- src/lib/Dungeon.js
The automation filter was always disabled while running a dungeon automation.
It's now only disabled if not automation process was asked for.
> Focus.Pokerus: Fixup dungeon catch logic

- Readme.md
- src/lib/Dungeon.js
The `handleClick` method was renamed `handleInteraction` in the new version
Introduced by [this commit](https://github.com/pokeclicker/pokeclicker/commit/066f72ce014517a460daf54aa39288641683b368)
Fixes #305
> Dungeon: Fixup v0.10.12 regression

- src/lib/BattleFrontier.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Menu.js
v0.10.14 introduced ClearBattleFrontier quests.
When this quest is active, it will be picked after any other handled type of quests.
The player will be moved to Battle Frontier town.
The BattleFrontier mode will be entered and the session will start automatically (from the last checkpoint, if any).
When the quest objective is met, or the automation is turned off, the BattleFrontier mode will be left.
Fixes #312
> Focus.Quest: Add support for the new BattleFrontier quest

- src/lib/Utils/Gym.js
- tst/stubs/Gym/Gym.pokeclicker.stub.js
Since [v0.10.2](https://github.com/pokeclicker/pokeclicker/commit/f02f836c5ace9c0a7e4a7c8b63ccb1e6beda84b8) a gym leader might have more potential pokémons listed than the ones that are actually used.
This would lead to many wrong decisions for the automation. The `getPokemonList()` is now used to access the correct pokémon list.
Fixes #307
> Utils.Gym: Improve best option selection

- src/lib/Utils/Battle.js
It seems that getBonus() now includes the achievement bonus, so the copy of the calculateClickAttack method is out of date and applies the achievement bonus multiplier twice.
This results in a choice of route/gym that cannot be completed in a single click, greatly reducing efficiency.
> fix(calculateClickAttack): Fix achievement bonus counted twice

- src/lib/Dungeon.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
The dungeon automation did not stop when disabling Focus automation. The Focus now always set the StopAfterThisRun flag on exit.
If the Dungeon automation starts with such flag, it will automatically switch to the default None mode.
> Focus: Fixup dungeon not stopping on exit

- src/ComponentLoader.js
- src/lib/Dungeon.js
- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Focus/ShadowPurification.js
- src/lib/Utils/Pokeball.js
The shadow pokémons were introduced in the v0.10.14 update. 
Such pokémon only appear in the new Orre sub-region of Hoenn.
Capturing Shadow pokémon will update their status and they will need to be purified at the Purify Chamber.
This new "Focus on" feature will automatically move to dungeons were there is at least one uncaught shadow pokémon.
It will equip the configure the pokémon catching filter to catch every uncaught shadow pokémon.
Once every shadow pokémon are captured, it will then move to the next dungeon.
The dungeon will try to purify pokémons between each run.
Once all available shadow pokémons are caught, the automation will farm Exp and Purify the remaining shadow pokémons.
Fixes #321
> Focus.ShadowPurification: Implement this new feature

- src/lib/Instances/Safari.js
If the player exists the Safari while the automation is enabled it will now be disabled.
Part of #49
> Safari: Stop the automation on player exit

- src/lib/Instances/Safari.js
- src/lib/Menu.js
The panel is now duplicated in the safari battle modal so that the user can interact with it in such case.
Part of #49
> Safari: Make the panel accesible while in battle

- Readme.md
- src/lib/Focus/Quests.js
The pokeclicker/pokeclicker@91337006a478a72264fc4e1d9a4ddb8ad5b51771 commit homogenized quests names, resulting in the battle frontier quest automation to fail.
The ClearBattleFrontierQuest class is now matched properly again.
Fixes #335
> Focus.Quest: Fixup v0.10.18 regression

- Readme.md
- src/lib/Utils/Pokeball.js
The v0.10.18 added a setting to invert the filter priority order.
The automation now puts its filter to the top when this new setting is disabled and to the bottom when enabled.
Fixes #337
> CatchFilters: Handle v0.10.18 new order setting

- src/lib/Menu.js
The button was 8px to high compared to the rest of the line
> Hatchery: Fixup sorting button miss-alignment

- .github/workflows/tests.yml
- src/lib/Farm.js
- tst/tests/Farm/UnlockStrategies.test.in.js
The Sprinklotad Oak item can mutate the Watmel berry into a Shuca, ruining the strategy
It should prevent #344 from happening, as long as the user did not disable the `Update oak item loadout when needed` advanced setting
> Farm: Forbid the Sprinklotad for pinkan unlock

- src/lib/Focus/PokerusCure.js
- src/lib/Focus/ShadowPurification.js
The disableAutomationFilter function was moved to the Pokeball class. 
It was not updated everywhere in the codebase.
The right class is now used everywhere.
> Focus: Fixup pokeball filter crash

- src/lib/Instances/Safari.js
When an instance of the Safari was completed, and a new one was started, the path to the farm area was not refreshed. 
This resulted in the player going to the previous run location, often not a Grass of Water location.
This could cause crashes as well, if the user resized their browser window, since the size of the safari grid depends on the browser size.
The internal data is now properly reset between each run.
> Safari: Fixup problem when entering a new instance

- src/lib/Instances/Safari.js
The default was always set to false during Automation start-up. It's now only set if no value was previously set.
---
When the following case occurred:
(With the target area in red)
The automation was stuck and never moved.
The automation target order was changed to prevent this to occur.
> Safari: Fixup repeat type reseting to "only-once"

- src/lib/Instances/Safari.js
The repeat button initial state was always "repeat-once", dispite the localstorage value.
The saved value is now considered properly.
> Safari: Fixup repeat button initial state

- src/lib/Farm.js
- src/lib/Focus/Achievements.js
Orre quests are now set to be handled at the same time as Sinnoh ones
Fixes #355
> Focus.Achievements: Handle Orre quests

- src/lib/Focus/Quests.js
- src/lib/Focus/ShadowPurification.js
- src/lib/Instances/Dungeon.js
The automation will try to kill two birds with one stone when both `Defeat the <Dungeon> <n> times` and `Catch <n> Shadow Pokémon` quests are active.
It will now only try to capture shadow pokémons the former quest's dungeon if it can have shadow pokémons.
Fixes ? #359
> Focus.Quests: Don't try to catch shadows if dungeon doesn't have any

- src/lib/Focus.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Utils/Route.js
- tst/stubs/GameConstants.pokeclicker.stub.js
- tst/stubs/MapHelper.pokeclicker.stub.js
- tst/stubs/Player.pokeclicker.stub.js
- tst/tests/Utils/Route.test.in.js
The new version 0.10.20 juste came out a broke some interfaces.
This PR fixes the most obvious ones (hopefully the only ones) : 
- `Currency` is now only accessible via `GameConstants`
- `player.route` is not a callback anymore
Adresses (part of) #363
> v0.10.20 regressions fixup

- Readme.md
- src/lib/Hatchery.js
- tst/imports/Pokeclicker.import.js
- tst/stubs/Category.pokeclicker.stub.js
- tst/stubs/Pokemon/PartyPokemon.pokeclicker.stub.js
- tst/tests/Hachery/AutoHatchery.test.in.js
Adresses #270 
I was interested in this feature ! I too wanted to prioritize my roster pokemons while being able to sort on breading efficiency for example.
I also added a watcher to update the select whenever categories are updated by the user.
Because this feature is likely to be the most restrictive (least amount of positive matches), I believe it's most efficient to use it as the very first sort option.
> Hatchery: Add Category sorting priority

- src/lib/Farm.js
- src/lib/Focus/Quests.js
The automation filter was never cleared and any previously set restriction would temper with the capture.
The filter is now reset properly
Fixes #371
> Focus.Quests: Fixup pokéball filter for shadow quests

- src/lib/Click.js
- src/lib/Menu.js
- src/lib/Utils.js
An advanced settings panel is now available for click attack with an option to configure click interval.
This option only accepts integer values greater or equal to 50 (which is the in-game hard-cap for clicks).
Fixes #374
> Click: Make click interval configurable

- src/lib/Click.js
- src/lib/Focus/Achievements.js
- src/lib/Focus/Quests.js
- src/lib/Menu.js
- src/lib/Shop.js
The player might not want to do every single achievements, especially the high amount ones.
Toggles are now available in the advanced settings to choose which one to perform, or skip :
Part of #97
> Focus.Achievements: Make types skippable

- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Focus/ShadowPurification.js
Found a small bug on Focus' that can self-disable. If the focus has nothing to do from the start, it disables itself right away but doesn't reset any "forced" modes.
For instance, on a save where every Pokémon is purified, enabling the ShadowPurification Focus will permanently disable the Click Automation toggle. I haven't found a way to unlock the button without reloading the game.
This is due to the fact that the loop is started before the forced modes are set. Meaning that the loop will run once, self-disable (which will reset any forced modes), and only then will the forced modes be set.
Simply starting the loop at the end of the initialization solves this issue 🚀
> Focus: Fixup force enabled modes

- src/lib/Focus/Quests.js
- src/lib/Utils/Battle.js
- src/lib/Utils/Gym.js
- tst/imports/Pokeclicker.import.js
- tst/stubs/GameConstants.pokeclicker.stub.js
- tst/stubs/Items/HeldItem.pokeclicker.stub.js
- tst/stubs/Pokemon/PartyPokemon.pokeclicker.stub.js
- tst/tests/Utils/Gym.test.in.js
Hi !
Improved the accuracy of gym's gems/tick computation. As pointed at by the todo, health difference between Pokémons wasn't properly taken into account. The difference is minor but gets at bit bigger in the late game.
For instance if one pokémon is defeated in 1 tick and another in 3 ticks: previous calculation yields `((5/3) + (5/1)) / 2 = 3.333 gems/t`, instead it should yield `(5+5) / (3+1) = 2.5 gems/t`. Simplified to "in a total of 4 ticks we would get 10 gems".
The current click attack computation wasn't taking Purified pokémons into account, which also give a +100% bonus.
I took the opportunity to update the calculation method to get closer to the one currently used by the game. That is by using `PartyPokemon.clickAttackBonus`, introduced in v0.10.18, which computes (and …
> Improve Gym for Gem and click attack computation

- Readme.md
- src/lib/Focus/Quests.js
- src/lib/Menu.js
- src/lib/Underground.js
The v0.10.23 update includes a major rework to the Underground feature.
That includes completely removing daily deals and chains.
Instead, players will be able to trade items of the same type at a rate of 3 to 1 at any time.
For example, shards can be traded for other shards, plates can either
be sold for gems or traded for other plates,
and diamond items can only be sold for diamonds.
---
For now the feature has been disabled completely : 
The trade feature has been removed, since it's not a thing anymore.
Fixes #386
> Mine: Disable Underground automation

- src/lib/Underground.js
The user can search for a new mine, in such case don't try anything until the timer is elapsed.
Part of #389
> Mine: Don't do anything while searching for a new mine

- src/lib/Underground.js
Once the player reaches a certain Underground level, the tools can be used without any cooldown.
In such case, it's pointless to prioritize maximized bomb use.
Part of #389
> Mine: Don't prioritize bombs with infinite durability

- src/lib/Instances/Dungeon.js
If the user sets a pokéball type to catch bosses and the automation forced a dungeon run, it would cause the automation setting to be overridden and it would never go back to the proper one.
The catch settings are now only changed if no automation mode is set.
> Dungeon: Don't change catch settings during automation mode

- src/lib/Instances/Dungeon.js
When the panel was hidden while the advanced settings were opened, it made the other advanced settings inaccessible.
The advanced settings are now closed upon hiding.
> Dungeon: Close the advanced settings when hiding the panel

- src/lib/Focus.js
- src/lib/Focus/PokerusCure.js
- src/lib/Focus/Quests.js
- src/lib/Focus/ShadowPurification.js
- src/lib/Instances/Dungeon.js
- src/lib/Menu.js
- src/lib/Utils.js
The drop-down list for both `Focus` and `Dungeon` panels now list all available pokéballs.
Since it can be a bit difficult to identify each pokéball by only its name, the corresponding image is now displayed in the list as well: 
---
In case the player runs out of the selected ball, the `Focus` feature will:
- Buy new one if it can be using Money
- Stop and display a warning message if its only available in a currency other than money
Closes #384
> Menu: Allow every pokeball in drop-down lists

- src/lib/Focus/PokerusCure.js
- src/lib/Focus/ShadowPurification.js
- src/lib/Utils/Route.js
Trainer shadow pokemons can be caught.
The script now considers those for dungeons.
Fixes #403
> Focus.PokerusCure: Support trainer shadow pokemons
