Farigh/pokeclicker-automation

src/ComponentLoader.js

Some scripts depends on others. The former needs to be loaded
after the later.
It's now possible to set multiple dependency depth.

ComponentLoader: Rework dependency management

---

src/lib/Dungeon.js

If the player enables the dungeon completion mode after moving in the dungeon, or moves while the completion in progress, the following will occur:
- If the boss is visible:
- Collect all visible chests
- Defeat the boss
- Turn off the feature (since the player is most likely wanting
to do the path finding manually)
- If not:
- Go to the 1st visited tile of the bottom-most row
- Proceed with the standard behavior
- Turn off the feature once the boss is defeated (for the same reason)
Fixes #15

Dungeon: Detect any player interaction

---

src/Automation.js
src/ComponentLoader.js
src/lib/Click.js
src/lib/Dungeon.js
src/lib/Farm.js
src/lib/Focus.js
src/lib/Focus/Achievements.js
src/lib/Focus/Quests.js
src/lib/Gym.js
src/lib/Hatchery.js
src/lib/Items.js
src/lib/Menu.js
src/lib/Quest.js
src/lib/Trivia.js
src/lib/Underground.js
src/lib/Utils.js

The quest feature is very similar to the Achievement topic and can't be used at the same time.
It's pretty logical to merge this feature into the 'Focus on' one.
Fixes #13

Convert the quests feature to a focus topic

---

src/lib/Farm.js
src/lib/Utils/OakItem.js
src/lib/Utils/Route.js

The v0.9.6 renamed Poison_Barb to Rocky_Helmet

v0.9.6 update fixes

---

src/lib/Focus.js
src/lib/Focus/Achievements.js
src/lib/Focus/Quests.js
src/lib/Utils/Gym.js
src/lib/Utils/OakItem.js

Some focus topics did not choose any loadout.
The Money loadout was created, since the exp one can be better
optimize without the need of money making.
Fixes #39

Focus: Choose the most appropriate loadout

---

src/.vscode/settings.json
src/Automation.js
src/lib/Click.js
src/lib/Dungeon.js
src/lib/Farm.js
src/lib/Focus.js
src/lib/Focus/Achievements.js
src/lib/Focus/Quests.js
src/lib/Gym.js
src/lib/Hatchery.js
src/lib/Items.js
src/lib/Menu.js
src/lib/Trivia.js
src/lib/Underground.js
src/lib/Utils.js
src/lib/Utils/Gym.js
src/lib/Utils/LocalStorage.js
src/lib/Utils/OakItem.js
src/lib/Utils/Route.js

Internal methods should start with `__internal__`.
Internal methods shared with other sub-classes of the same feature
should start with `__`.
Public method should __NOT__ start with `__`.

Homogenize coding-style

---

src/lib/Dungeon.js
src/lib/Farm.js
src/lib/Focus.js
src/lib/Focus/Achievements.js
src/lib/Focus/Quests.js
src/lib/Gym.js
src/lib/Hatchery.js
src/lib/Items.js
src/lib/Menu.js
src/lib/Shop.js

An advanced settings panel was added to the dungeon auto fight feature.
The following settings are available:
- Rush boss as soon as it's been found
- Don't pick any chests
Fixes #54

Dungeon: Add some completion strategy options

---

.github/workflows/tests.yml
Readme.md

On startup, the app will check if the scripts are installed, or if a newer version is available, and will install it locally.
This will allow the player to benefit from the automation even without an internet connexion, as the pokeclicker app does.

Desktop: Add offline support for the automation

---

src/lib/Click.js
src/lib/Focus.js
src/lib/Utils/Battle.js
src/lib/Utils/Gym.js
src/lib/Utils/Route.js
tst/imports/Pokeclicker.import.js
tst/stubs/App.pokeclicker.stub.js
tst/stubs/Challenges.pokeclicker.stub.js
tst/stubs/Currency/Wallet.pokeclicker.stub.js
tst/stubs/GameConstants.pokeclicker.stub.js
tst/stubs/Gym/Champion.pokeclicker.stub.js
tst/stubs/Gym/Gym.pokeclicker.stub.js
tst/stubs/Gym/GymList.pokeclicker.stub.js
tst/stubs/Gym/GymPokemon.pokeclicker.stub.js
tst/stubs/Pokemon/PokemonFactory.pokeclicker.stub.js
tst/stubs/Route/RegionRoute.pokeclicker.stub.js
tst/stubs/Route/RouteHelper.pokeclicker.stub.js
tst/stubs/Route/RoutePokemon.pokeclicker.stub.js
tst/stubs/Route/Routes.pokeclicker.stub.js
tst/stubs/Town/DungeonTown.pokeclicker.stub.js
tst/stubs/Town/Town.pokeclicker.stub.js
tst/stubs/Town/TownContent.pokeclicker.stub.js
tst/stubs/Town/TownList.pokeclicker.stub.js
tst/tests/Farm/UnlockStrategies.test.in.js
tst/tests/Hachery/AutoHatchery.test.in.js
tst/tests/Utils/Battle.test.in.js
tst/tests/Utils/Gym.test.in.js
tst/tests/Utils/Route.test.in.js
tst/utils/PokemonLoader.utils.js

The feature will now be hidden if the challenge is active.
The player click attack will not be considered anymore, if the player turned off the feature or the challenge is active.
(Some still force the auto-click if the challenge is not active, is such case the click attack will be considered)
Fixes #44

Click: Handle no-click challenge

---

src/lib/Farm.js
tst/tests/Farm/UnlockStrategies.test.in.js

The Kasib berry requires any berry to wither to have a chance to
appear in the plot.
The regular strategy was used for this unlock, which plants Cheri
berries. However, those were harvested right before dying, instead
of letting those die.
The harvest strategy now contains the following possible appoach:
- AsSoonAsPossible
- RightBeforeWithering
- LetTheBerryDie
The latest is now used for the Kasib unlock
Fixes #132

Farm: Wait for berries withering while trying to unlock Kasib

---

src/lib/Dungeon.js

The strategy did not change, it's just now applied to each floor. 
The ladder will automatically be used based on the selected strategy. 
If the chest are set to be collected, it will be done for the current stage right before moving to the next stage.
Fixes #142

Dungeon: Handle multiple floor dungeons

---

src/lib/Underground.js

Acording to the code, this did something similar in the past.
This pull request simply makes the mining loop use as many restore items as it is needed to be able to use a bomb, so the loop does not run out of things to do.

Mining: Use restore items faster for continuous mining

---

src/lib/Underground.js

More low-hanging fruit
Feel free to rephrase how the toggle or notifications are worded

Mining: Add an option to automatically do all diamond-positive daily deals

---

src/lib/Trivia.js

It's sometimes difficult to know if all roamers were already caught. 
The pokeclicker catch indicator is now displayed.
The caught status of each roamers was added to the tooltip as well.
---
The roamers route name can be pretty long in the later regions.
The name could overflow the menu width.
Additionally, the route names are not only numbers, and finding
the route location can be a bit tricky (even more with subregions).
The route name in now displayed in the tooltip and a button is
available to jump right there.

Trivia: Improve roamers info

---

src/lib/Trivia.js

Fixes #120
There are a few changes to do:
* Format the region name (I dont know where that is, currently I'm taking the name from the `GameConstants`, which leaves "alola" instead of "Alola", and "sevii4567" instead of "Sevii Islands 4567")
* (Optional) Show all towns with quests, instead of only the first one
* (Optional) Show the name of the quest or quests in the panel
* (Optional) Slow down the refresh. Maybe once every minute?
* (Optional) Add a "Go to" button. This might allow some unintended movement, like leaving a region before the port is discovered. Not sure if there is a check for it already somewhere.

Trivia bulletin board

---

src/lib/Hatchery.js
src/lib/Menu.js
tst/imports/Pokeclicker.import.js
tst/stubs/SortOptions.pokeclicker.stub.js
tst/tests/Hachery/AutoHatchery.test.in.js

Fixes #48 (or at least the part to "Sort by other properties than Breeding efficiency". EVs is also included in the list of attributes, but it might not be what is wanted for it)

Hatchery: Add custom sorting and ordering

---

src/lib/Shop.js

Fixup pokédollar typo

---

src/lib/Click.js
src/lib/Trivia.js

This PR fixes the issues introduced in the 0.10.2 version.
I'm not totally sure about the change to `player.starter()`, as I dont know what it was checking.
There are many things features we might want to add because of this update. I will create the issues for that separately
Fixes #202

FIx: Fix to changes at 10.2 update

---

src/lib/Click.js
src/lib/Utils/Route.js

Fixes #24
Marked as draft as it requires the base pokeclicker game to publish the current develop branch.
However, when that happens, the trivia itself will break because of #186

Trivia: Fix subregion travel

---

src/lib/Hatchery.js

The mega evolutions have an minimum base attack increase requirement.
This new option will breed pokemon that do not match such requirement in priority.
Fixes #201

Hatchery: Add UnlockMegaEvolutions setting

---

src/Automation.js
src/ComponentLoader.js
src/lib/BattleFrontier.js
src/lib/Gym.js

It is very simple. If the battle frontier finishes, it restarts it. If the player manually left it, it disables itself.
No other logic to it
Edit: Implements (part) of #150 
Fixes #150

BattleFrontier: Add the battle frontier automation

---

src/lib/BattleCafe.js
src/lib/Dungeon.js
src/lib/Focus.js
src/lib/Focus/Achievements.js
src/lib/Focus/Quests.js
src/lib/Gym.js
src/lib/Menu.js
src/lib/Trivia.js
src/lib/Utils.js

The user can now choose which ball to equip before fighting the boss.
Choosing None will keep the in-game setting unchanged.
Fixes #154

Dungeon: Add a setting to catch dungeon bosses

---

src/lib/Dungeon.js

Since v0.10.9 the flashlight can reveal tiles beyond the immediate nearby tile. This caused the player not being able to move to the most beneficial tile in most case, since it would not be accessible.
Only the accessible tiles are now considered instead of all visible tiles.
This fixup still has some flows with the chest collection process.
Addresses most of #233

Dungeon: Restore the flash-light strategy

---

src/lib/Hatchery.js

Those sub-regions are peculiar and deserves dedicated filters.
The filters are only added for the region filter, not the other lists.
Fixes #238

Hatchery: Add Sevii Island and Magikarp Jump regions

---

src/lib/Trivia.js

Store most informations instead of iterating over the whole game's town list each time.

Trivia: Improve perfs

---

src/lib/Trivia.js

Only store inactive quests.
Don't bother with boards in region that the player does not have access to, yet.
Update inactive quests list every time the trivia listing gets updated.

Trivia: some more perf improvement

---

src/lib/Items.js

The Oak Items and Gems auto upgrade feature will now be respectively stopped and hidden once every possible elements have been maxed-out.

AutoUpgrade: Hide feature when everything is maxed out

---

src/lib/Dungeon.js
src/lib/Focus/PokerusCure.js

Once all routes are cured, the automation will now move on with dungeons.
Part of #122

Focus.PokerusCure: Add dungeons to the possible locations

---

src/lib/Focus/PokerusCure.js

The game method RouteHelper.getAvailablePokemonList only uses the player's current region weather.
Using it from another region might result in incorrect values. 
The automation now performs the check using the targeted region weather
Related to #122

Focus.PokerusCure: Handle Weather requirements properly

---

src/lib/Farm.js

This should be useful when doing unattended farming of berries with a long growth time without having to spend more rich mulch than necessary.

Farming: Add feature to apply rich mulch before harvesting

---

Readme.md
src/lib/Trivia.js

The v0.10.10 added more detailed hints for mega evolution that are locked.
The condition was updated accordingly.

Trivia: Fixup Mega evolution not being filtered correctly

---

src/lib/Utils/Pokeball.js

Focus.Pokerus: fixup "Pokerus is not defined" error

---

src/lib/BattleFrontier.js
src/lib/Dungeon.js
src/lib/Gym.js

The Crush Kin image was moved to the npcs directory in v0.10.11

Fixup image location

---

src/lib/Dungeon.js

The dungeon auto-fight feature now allows 4 "stop on" modes:
- Uncaught pokémons
- Uncaught shiny pokémons
- Uncaught shadow pokémons
- Uncaught shadow shiny pokémons
Prerequisite of #321

Dungeon: Add support for Shadow pokémons

---

src/lib/Instances/Safari.js
src/lib/Menu.js

A new button was added that can set either of those 2 modes:
- One run, then stop
- Infinit reruns
Part of #49

Safari: Add the option to stop after 1 run

---

src/lib/Hatchery.js
src/lib/Menu.js
src/lib/Underground.js
tst/stubs/Player.pokeclicker.stub.js
tst/stubs/Underground/Underground.pokeclicker.stub.js
tst/stubs/Underground/UndergroundItem.pokeclicker.stub.js
tst/stubs/Underground/UndergroundItems.pokeclicker.stub.js
tst/tests/Hachery/AutoHatchery.test.in.js

The mining items were merged with the other items via this commit: pokeclicker/pokeclicker@25d0376f8ddb5cb828afaa6b1b18ca8bb16e789a
The new representation is now used.
The tests were commented to allow the patch to go through faster and will be fixed in an upcoming commit.
Fixes #332
Fixes #333

Fixup v0.10.18 regressions

---

src/lib/Utils/Pokeball.js

The previous PR missed 2 observables.
It's now done properly
Fixes #339

Utils.Pokeball: Fixup regression

---

src/lib/Focus/Quests.js

The description mentionned Fire gems where it could be any type of gems

Focus.Quests: Fixup GainGemsQuest description

---

src/lib/Focus/PokerusCure.js

If the user checked the `Skip as many fights as possible`
advanced settings, the automation will to the boss directly
if no other pokemon needs curing.
Fixes #291
---
Focus.PokerusCure: Fixup weather requirement for dungeons
The weather requirement is based on the player's current region.
The automation needs to check it based on the destination region.
The check was performed correctly for routes, but it was not the case
for dungeon. It's now correctly checked for both cases.

Focus.PokerusCure: Skip unneeded fights

---

src/lib/Instances/Safari.js

The safari now has an advanced setting (only available in the main panel).
The first added setting makes the automation throw baits at pokémons until all bait throwing related achievements are completed.
The setting is disabled by default and can be found in the advanced settings panel : 
This panel is not accessible in a battle : 
Part of #49

Safari: Add bait achievement advanced setting

---

src/lib/Farm.js

Wandering pokémons are not caught automatically anymore. The player has to click the plot to use a pokéball and catch it.
The automation now features a wanderer auto-catch setting. It is enabled by default.
Fixes #369

Farm: Auto-catch wanderers

---

src/lib/Underground.js
tst/stubs/Underground/UndergroundController.pokeclicker.stub.js

As a first-intention implementation, the automation will perform the following actions:
- Survey will be used as soon as available
- If equipped, the battery discharge will be used as soon as charged
- Bombs will be used as soon as available
A more elaborate version will be implemented latter on.
Part of #389

Mine: Add a simplistic automation

---

src/lib/Focus/Quests.js
src/lib/Underground.js

The new algorithm performs the following actions, in that order:
- Survey will be used as soon as available, unless all items were already found
- If equipped, the battery discharge will be used as soon as charged
- Bombs will be used as soon as available, unless all items were already found
- If the bomb's durability is maxed-out, it will be used regardless
- Then it tries to use the best possible tool to:
- Complete a partially found item
- Find a hidden item
Partially adresses #389

Mine: Implement the new algorithm

---

src/lib/Underground.js

The chisel move with the less use needed to reveal its cell is now used
Part of #389

Mine: Improve Chisel use when trying to find new items

---

src/lib/Instances/BattleCafe.js
src/lib/Utils.js

The alignment have been broken, it's now fine again :

BattleCafe: Fixup catch status alignment

---

Readme.md
src/lib/Hatchery.js
tst/stubs/GameConstants.pokeclicker.stub.js
tst/stubs/Hatchery/Breeding.pokeclicker.stub.js
tst/utils/PokemonLoader.utils.js

The v0.10.24 removed fossil from the hatchery.
The new fossil revive feature replaced it.
Fixes #411

Hatchery: Remove fossil feature

---

src/lib/Hatchery.js
src/lib/Underground.js
tst/tests/Hachery/AutoHatchery.test.in.js

Since v0.10.24, the bomb has a 87.5% destruction rate when hitting
a tile with a visible item.
An option was added to prevent using bombs when an item is visible.
This option is enabled by default.
Fixes #412

Mine: Add safe bombs advanced setting

---

src/lib/Focus/PokerusCure.js

The dungeon pokemonList contained too some unavailable pokémons. 
The dungeon normalEncounterList is now used.
It has the added benefit to contain trainers shadow pokémons as well as mimic pokémons.
For now mimics are skipped, their support might be added in a futur update.
Fixes #409

Focus.PokerusCure: Fixup some dungeon runs on completed dungeons
